name: Dropbox Upload

on:
  push:
    branches: [ main ]  # Adjust this to your needs

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # Adjust this to your Node.js version
    - name: Install dependencies
      run: npm ci
    - name: Run Dropbox upload script
      env:
        CLIENT_ID: ${{ secrets.CLIENT_ID }}
        CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
        DROPBOX_ACCESS_TOKEN: ${{ secrets.DROPBOX_ACCESS_TOKEN }}
      run: node src/dropbox.js  # Adjust this path if necessary