name: Purge

on:
  push:
    branches:
      - main

jobs:
  purge:
    runs-on: ubuntu-latest

    steps:
    - name: Call jsDelivr purge URL
      run: curl -X GET https://purge.jsdelivr.net/gh/pixelsock/quoteApp@latest/dist/bundle.js